### PR TITLE
Update closed loop server with new interface

### PR DESCRIPTION
**Pull request by wljungbergh**
Update the closed-loop server

- Removing `async` definitions 
- Serialize tensor directly instead of converting to PNG :zap:

### CODE REVIEW

**Comment by atonderski** [comment]
I wonder if it would be better to allow for both raw tensors as well as actual images. Raw tensors are great if running on the same local connection (or even machine), but it could be horribly slow in other settings.

**Comment by atonderski** [comment]
maybe something like this:
```
class ImageFormat(str, Enum):
    raw = "raw"
    png = "png"
    jpg = "jpg"

@app.get("/image/")
async def get_image(format: Optional[ImageFormat] = Query(None, description="Image format (raw, png, jpg)")):
    if not format:
        format = ImageFormat.jpg

    image_bytes = get_image_bytes(format.value)  # Assuming get_image_bytes() method exists

    # Yours truly chatgpt suggested this, dunno if nice
    if format == ImageFormat.raw:
        return StreamingResponse(iter([image_bytes]), media_type="image/jpeg")
    elif format == ImageFormat.png:
        return StreamingResponse(iter([image_bytes]), media_type="image/png")
    elif format == ImageFormat.jpg:
        return StreamingResponse(iter([image_bytes]), media_type="image/jpeg")
```

**Comment by wljungbergh** [comment]
I like it. I added options for raw, png, and jpeg/jpg. However, I didn't change to the streaming response for now.

**Comment by wljungbergh** [comment]
Note that I also changed the `render_image` endpoint from a `POST` to `GET`. Also changed the name.

**Review by atonderski — APPROVED** [review]
thanks for fixing, lgtm now!

**Pull request merged**
